package pojos;
// Generated 05-May-2018 13:39:31 by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private int accountNum;
     private Customer customer;
     private Integer sortCd;
     private Integer balance;
     private String accountType;
     private String transactList;

    public Account() {
    }

	
    public Account(int accountNum, Customer customer) {
        this.accountNum = accountNum;
        this.customer = customer;
    }
    public Account(int accountNum, Customer customer, Integer sortCd, Integer balance, String accountType, String transactList) {
       this.accountNum = accountNum;
       this.customer = customer;
       this.sortCd = sortCd;
       this.balance = balance;
       this.accountType = accountType;
       this.transactList = transactList;
    }
   
    public int getAccountNum() {
        return this.accountNum;
    }
    
    public void setAccountNum(int accountNum) {
        this.accountNum = accountNum;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Integer getSortCd() {
        return this.sortCd;
    }
    
    public void setSortCd(Integer sortCd) {
        this.sortCd = sortCd;
    }
    public Integer getBalance() {
        return this.balance;
    }
    
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }
    public String getTransactList() {
        return this.transactList;
    }
    
    public void setTransactList(String transactList) {
        this.transactList = transactList;
    }




}


