package pojos;
// Generated 05-May-2018 13:39:31 by Hibernate Tools 4.3.1



/**
 * Bank generated by hbm2java
 */
public class Bank  implements java.io.Serializable {


     private int id;
     private Byte customerLoggedIn;
     private String customerList;

    public Bank() {
    }

	
    public Bank(int id) {
        this.id = id;
    }
    public Bank(int id, Byte customerLoggedIn, String customerList) {
       this.id = id;
       this.customerLoggedIn = customerLoggedIn;
       this.customerList = customerList;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Byte getCustomerLoggedIn() {
        return this.customerLoggedIn;
    }
    
    public void setCustomerLoggedIn(Byte customerLoggedIn) {
        this.customerLoggedIn = customerLoggedIn;
    }
    public String getCustomerList() {
        return this.customerList;
    }
    
    public void setCustomerList(String customerList) {
        this.customerList = customerList;
    }




}


