package pojos;
// Generated 05-May-2018 13:39:31 by Hibernate Tools 4.3.1



/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private int transId;
     private String transType;
     private Integer date;
     private String description;
     private Integer amount;
     private Integer accountTo;
     private Integer accountFrom;

    public Transaction() {
    }

	
    public Transaction(int transId) {
        this.transId = transId;
    }
    public Transaction(int transId, String transType, Integer date, String description, Integer amount, Integer accountTo, Integer accountFrom) {
       this.transId = transId;
       this.transType = transType;
       this.date = date;
       this.description = description;
       this.amount = amount;
       this.accountTo = accountTo;
       this.accountFrom = accountFrom;
    }
   
    public int getTransId() {
        return this.transId;
    }
    
    public void setTransId(int transId) {
        this.transId = transId;
    }
    public String getTransType() {
        return this.transType;
    }
    
    public void setTransType(String transType) {
        this.transType = transType;
    }
    public Integer getDate() {
        return this.date;
    }
    
    public void setDate(Integer date) {
        this.date = date;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public Integer getAccountTo() {
        return this.accountTo;
    }
    
    public void setAccountTo(Integer accountTo) {
        this.accountTo = accountTo;
    }
    public Integer getAccountFrom() {
        return this.accountFrom;
    }
    
    public void setAccountFrom(Integer accountFrom) {
        this.accountFrom = accountFrom;
    }




}


